site_name: wagtail-marketing-addons
site_description: An (opiniated) set of tools to help marketeers in their day-to-day jobs.
repo_url: https://github.com/lukkien/wagtail-marketing-addons
theme: readthedocs

markdown_extensions:
  # Allows index.md to include the repo root README.
  - 'pymdownx.snippets':
      check_paths: True

# http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - About: index.md
  - 'Getting started': getting_started.md
  - 'Available settings': available_settings.md
