site_name: wagtail-marketing-addons
site_description: An (opiniated) set of tools to help marketeers in their day-to-day jobs.
repo_url: https://github.com/lukkien/wagtail-marketing-addons

theme: readthedocs
use_directory_urls: true

markdown_extensions:
  # Allows index.md to include the repo root README.
  - 'pymdownx.snippets':
      check_paths: true
  - toc:
      permalink: true
      toc_depth: 2

# http://www.mkdocs.org/user-guide/writing-your-docs/#configure-pages-and-navigation
nav:
  - 'Home': index.md
  - 'Getting started': getting_started.md
  - 'Features': features.md
  - 'Available settings': available_settings.md
  - 'Release notes': 'changes.md'
